#ifndef APP_TASK_CONFIG_H
#define APP_TASK_CONFIG_H

#define APP_TASK_PRIORITY_LED_DEMO   (tskIDLE_PRIORITY + 1U)
#define APP_TASK_STACK_SIZE_LED_DEMO 384U

#define APP_TASK_PRIORITY_EVENT      (tskIDLE_PRIORITY + 2U)
#define APP_TASK_STACK_SIZE_EVENT    384U

#define APP_TASK_PRIORITY_KEY_DEMO   (tskIDLE_PRIORITY + 1U)
#define APP_TASK_STACK_SIZE_KEY_DEMO 384U

#endif
