#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#include "stm32f1xx_hal.h"

#define BOARD_LED_STATUS_1_GPIO_PORT GPIOC
#define BOARD_LED_STATUS_1_GPIO_PIN  GPIO_PIN_2

#define BOARD_LED_STATUS_2_GPIO_PORT GPIOC
#define BOARD_LED_STATUS_2_GPIO_PIN  GPIO_PIN_3

#define BOARD_KEY_K1_PORT GPIOA
#define BOARD_KEY_K1_PIN  GPIO_PIN_0
#define BOARD_KEY_K1_IRQn EXTI0_IRQn

#define BOARD_KEY_K2_PORT GPIOC
#define BOARD_KEY_K2_PIN  GPIO_PIN_13
#define BOARD_KEY_K2_IRQn EXTI15_10_IRQn

#define BOARD_IRQ_PRIORITY_KEY_EXTI 6U
#define BOARD_IRQ_PRIORITY_UART     6U

#define BOARD_UART_DEBUG_INSTANCE USART1
#define BOARD_UART_DEBUG_TX_PORT  GPIOA
#define BOARD_UART_DEBUG_TX_PIN   GPIO_PIN_9
#define BOARD_UART_DEBUG_RX_PORT  GPIOA
#define BOARD_UART_DEBUG_RX_PIN   GPIO_PIN_10
#define BOARD_UART_DEBUG_BAUDRATE 115200U
#define BOARD_UART_DEBUG_DMA_TX_CHANNEL DMA1_Channel4
#define BOARD_UART_DEBUG_DMA_TX_IRQn    DMA1_Channel4_IRQn

#define BOARD_CLOCK_HSE_VALUE_HZ  8000000U
#define BOARD_CLOCK_SYSCLK_HZ     72000000U

#endif
